# Generated by Django 5.0.4 on 2024-04-24 08:04

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner_Images",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Banner",
                    models.CharField(
                        choices=[
                            ("About_Us_Banner", "About_Us_Banner"),
                            ("Carrer_Details_Banner", "Carrer_Details_Banner"),
                            ("Carrer_list_Baner", "Carrer_list_Baner"),
                            ("Home_Banner", "Home_Banner"),
                            ("Services_Banner", "Services_Banner"),
                        ],
                        max_length=60,
                    ),
                ),
                ("Title", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Created_at", models.DateTimeField(auto_now_add=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
                ("Image", models.ImageField(upload_to=website.models.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=255)),
                ("Phone", models.CharField(max_length=12)),
                ("Subject", models.CharField(max_length=255)),
                ("Message", models.TextField()),
                ("Created_at", models.DateTimeField(auto_now_add=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=255)),
                ("Phone", models.CharField(max_length=12)),
                ("Address", models.CharField(max_length=255)),
                (
                    "Latitude_Logitude",
                    models.CharField(
                        help_text="Right click on the google maps to get latitude and longitude",
                        max_length=50,
                    ),
                ),
                ("Facebook_link", models.URLField(default="www.facebook.com")),
                ("Instagram_link", models.URLField(default="www.instagram.com")),
                ("X_link", models.URLField(default="www.twitter.com")),
                ("Youtube_link", models.URLField(default="www.youtube.com")),
                ("Linkedin_link", models.URLField(default="www.linkedin.com")),
                ("Created_at", models.DateTimeField(auto_now_add=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Page_Type",
                    models.CharField(
                        choices=[
                            ("About_Us", "About_Us"),
                            ("Home", "Home"),
                            ("Carrers", "Carrers"),
                            ("Services", "Services"),
                        ],
                        max_length=60,
                    ),
                ),
                ("Page_Title", models.CharField(max_length=255)),
                ("Page_Content", models.TextField()),
                ("image", models.ImageField(upload_to="uploads/pages/%Y/%m/%d/")),
                ("Created_at", models.DateTimeField(auto_now_add=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
