# Generated by Django 5.0.4 on 2024-04-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactform",
            name="Phone",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="contactinfo",
            name="Phone",
            field=models.CharField(max_length=100),
        ),
    ]
