# Generated by Django 5.0.4 on 2024-04-25 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_contactform_phone_alter_contactinfo_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Banner_Images",
            new_name="BannerImage",
        ),
    ]
