# Generated by Django 5.0.4 on 2024-04-24 08:04

import django.db.models.deletion
import django_ckeditor_5.fields
import vacancies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jobs",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=255)),
                (
                    "Job_Type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "FULL_TIME"),
                            ("REMOTE", "REMOTE"),
                            ("HYBRID", "HYBRID"),
                            ("PARTIME", "PARTIME"),
                        ],
                        max_length=255,
                    ),
                ),
                ("About_Role", django_ckeditor_5.fields.CKEditor5Field(default="")),
                (
                    "Job_Requirement",
                    django_ckeditor_5.fields.CKEditor5Field(default=""),
                ),
                ("Open_date", models.DateField()),
                ("Close_date", models.DateField()),
                ("is_published", models.BooleanField(default=False)),
                ("Created_at", models.DateTimeField(auto_now_add=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidates",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=255)),
                ("Phone", models.CharField(default="123", max_length=10)),
                ("Created_at", models.DateTimeField(auto_now_add=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
                ("CV", models.FileField(upload_to=vacancies.models.get_upload_path)),
                (
                    "Position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vacancies.jobs"
                    ),
                ),
            ],
        ),
    ]
