# Generated by Django 5.0.4 on 2024-04-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidates",
            name="Phone",
            field=models.CharField(default="123", max_length=100),
        ),
    ]
