# Generated by Django 5.0.4 on 2024-04-25 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_alter_candidates_phone"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Candidates",
            new_name="Candidate",
        ),
        migrations.RenameModel(
            old_name="Jobs",
            new_name="Job",
        ),
    ]
